# Intro to data structures

In [1]:
import numpy as np
import pandas as pd

## Series

Series is a one-dimensional labeled array capable of holding any data type (integers, strings, floating point numbers, Python objects, etc.). The axis labels are collectively referred to as the index. The basic method to create a Series is to call: \\
```python
import pandas as pd
s = pd.Series(data, index=index) 
```

data can be many different things: 
- Python dict
- ndarray
- simple scalar value 

The passed index is a list of axis labels.

### Series from `ndarray`

In [ ]:
s = pd.Series(np.random.randn(5), index=["a", "b", "c", "d", "e"])
s1 = pd.Series(np.random.randn(5))
print(f'{s}\n')
print(s1) # Index as numbers (without specifying index)

a   -0.065456
b    1.247479
c   -1.023616
d    1.329032
e   -0.243313
dtype: float64

0    1.266768
1    0.431612
2   -0.657164
3    0.664100
4    0.933245
dtype: float64

In [4]:
s.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [5]:
s.array

<PandasArray>
[  -1.7446001521499273, -0.010954441162488969,    0.7031843965320795,
   0.31864468933965234,    0.4898719898011653]
Length: 5, dtype: float64

In [6]:
s.to_numpy()

array([-1.74460015, -0.01095444,  0.7031844 ,  0.31864469,  0.48987199])

### Series from dict

In [6]:
d = {"b": 1, "a": 0, "c": 2}
pd.Series(d)

b    1
a    0
c    2
dtype: int64

back to dictionary

In [ ]:
sd = pd.Series(d)
print(f'{sd}\n')

sd.to_dict()

b    1
a    0
c    2
dtype: int64

{'b': 1, 'a': 0, 'c': 2}

In [ ]:
from collections import OrderedDict, defaultdict
sd.to_dict(OrderedDict) #OrderedDict has a sequence

C:\Users\hanan\AppData\Local\Temp\ipykernel_15620\4020502850.py:2: FutureWarning: Starting with pandas version 3.0 all arguments of to_dict will be keyword-only.
  sd.to_dict(OrderedDict)

OrderedDict([('b', 1), ('a', 0), ('c', 2)])

### From scalar value
- Used for initialization

In [11]:
pd.Series(5.0, index=["a", "b", "c", "d", "e"])

a    5.0
b    5.0
c    5.0
d    5.0
e    5.0
dtype: float64

### Series is ndarray-like

In [14]:
s[0]

C:\Users\hanan\AppData\Local\Temp\ipykernel_15620\243613605.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s[0]

np.float64(-0.06545611677676502)

In [15]:
s[:3]

a   -0.065456
b    1.247479
c   -1.023616
dtype: float64

In [21]:
print(s>s.median())
s[s > s.median()] # Acts like boolean flag

a    False
b     True
c    False
d     True
e    False
dtype: bool

b    1.247479
d    1.329032
dtype: float64

In [17]:
s[[4,3,1]]

C:\Users\hanan\AppData\Local\Temp\ipykernel_15620\3287144557.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s[[4,3,1]]

e   -0.243313
d    1.329032
b    1.247479
dtype: float64

In [18]:
np.exp(s)

a    0.936640
b    3.481557
c    0.359294
d    3.777384
e    0.784026
dtype: float64

In [19]:
s.dtype

dtype('float64')

### Series is dict-like
- you can get and set values by index label

In [22]:
s

a   -1.744600
b   -0.010954
c    0.703184
d    0.318645
e    0.489872
dtype: float64

In [23]:
s["a"]

-1.7446001521499273

In [24]:
"d" in s

True

difference between s[] and s.get() (try with missing keys)

In [22]:
s.get("d")
s.get("f", np.nan) # If data doesn't exist
s.get("e",0)

np.float64(-0.24331252250219002)

## Vectorized operations and label alignment with Series
- When working with raw NumPy arrays, looping through value-by-value is usually not necessary. 
- The same is true when working with Series in pandas. Series can also be passed into most NumPy methods expecting an ndarray.

In [23]:
s

a   -0.065456
b    1.247479
c   -1.023616
d    1.329032
e   -0.243313
dtype: float64

In [24]:
s+s

a   -0.130912
b    2.494959
c   -2.047231
d    2.658063
e   -0.486625
dtype: float64

In [26]:
np.exp(s)

a    0.936640
b    3.481557
c    0.359294
d    3.777384
e    0.784026
dtype: float64

A key difference between Series and ndarray is that operations between **Series** automatically align the data based on label. Thus, you can write computations without giving consideration to whether the Series involved have the same labels.

In [28]:
s[1:]

b    1.247479
c   -1.023616
d    1.329032
e   -0.243313
dtype: float64

In [29]:
s[:-1]

a   -0.065456
b    1.247479
c   -1.023616
d    1.329032
dtype: float64

In [30]:
s[1:] + s[:-1]

a         NaN
b    2.494959
c   -2.047231
d    2.658063
e         NaN
dtype: float64

If unaligned, the result will be marked as missing NaN (or missing value will be considered as NaN value)

### Series name attribute
- name acts like an marker

In [31]:
s = pd.Series(np.random.randn(5), name="something")

In [34]:
s.name

'something'

## DataFrame

DataFrame is a 2D labeled data structure with columns of potentially different types. You can think of it like a spreadsheet or SQL table, or a dict of Series objects. It is generally the most commonly used pandas object. Like Series, DataFrame accepts many different kinds of input:

- Dict of 1D ndarrays, lists, dicts, or Series
- 2-D numpy.ndarray
- Structured or record ndarray
- A Series
- Another DataFrame

### From dict of Series or dicts

In [32]:
d = {
    "one": pd.Series([1.0, 2.0, 3.0], index=["a", "b", "c"]),
    "two": pd.Series([1.0, 2.0, 3.0, 4.0], index=["a", "b", "c", "d"]),
}
df = pd.DataFrame(d)
df

   one  two
a  1.0  1.0
b  2.0  2.0
c  3.0  3.0
d  NaN  4.0

You can specify the index (row label)

In [38]:
pd.DataFrame(d, index=["d", "b", "a"])

   one  two
d  NaN  4.0
b  2.0  2.0
a  1.0  1.0

You can specify the column (column label)\
since defined from dict (key value: one,two), will only call "two", leaving "three" column as all NaN values

In [35]:
pd.DataFrame(d, index=["d", "b", "a"], columns=["two", "three"])

   two three
d  4.0   NaN
b  2.0   NaN
a  1.0   NaN

In [36]:
df.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [37]:
df.columns

Index(['one', 'two'], dtype='object')

### From dict of ndarrays / lists
- no index is passed: the result will be range(n)

In [40]:
d = {"one": [1.0, 2.0, 3.0, 4.0], "two": [4.0, 3.0, 2.0, 1.0]}
pd.DataFrame(d)

   one  two
0  1.0  4.0
1  2.0  3.0
2  3.0  2.0
3  4.0  1.0

In [44]:
pd.DataFrame(d, index=["a", "b", "c", "d"])

   one  two
a  1.0  4.0
b  2.0  3.0
c  3.0  2.0
d  4.0  1.0

### From a list of dicts

In [47]:
data2 = [{"a": 1, "b": 2}, {"a": 5, "b": 10, "c": 20}]
pd.DataFrame(data2)

   a   b     c
0  1   2   NaN
1  5  10  20.0

In [43]:
pd.DataFrame(data2, index=["first", "second"])

        a   b     c
first   1   2   NaN
second  5  10  20.0

In [ ]:
pd.DataFrame(data2, columns=["a","b","d"])

   a   b   d
0  1   2 NaN
1  5  10 NaN

### From a dict of tuples
- Hierarchical input

In [ ]:
pd.DataFrame(
    {
        ("a", "b"): {("A", "B"): 1, ("A", "C"): 2},
        ("a", "a"): {("A", "C"): 3, ("A", "B"): 4},
        ("a", "c"): {("A", "B"): 5, ("A", "C"): 6},
        ("b", "a"): {("A", "C"): 7, ("A", "B"): 8},
        ("b", "b"): {("A", "D"): 9, ("A", "B"): 10},
    }
)

       a              b
       b    a    c    a     b
A B  1.0  4.0  5.0  8.0  10.0
  C  2.0  3.0  6.0  7.0   NaN
  D  NaN  NaN  NaN  NaN   9.0

### From a Series

- list(): seperates all indexes

In [61]:
ser = pd.Series(range(3), index=list("abc"), name="ser")
ser_noname = pd.Series(range(3), index=list("abc"))
ser

a    0
b    1
c    2
Name: ser, dtype: int64

In [56]:
display(pd.DataFrame(ser))
pd.DataFrame(ser_noname)

   ser
a    0
b    1
c    2

   0
a  0
b  1
c  2

### Column Selection, addition, deletion
- dataframe[key] = `series`

In [67]:
df["one"]

a    1.0
b    2.0
c    3.0
d    NaN
Name: one, dtype: float64

In [58]:
df["three"] = df["one"] * df["two"]
df

   one  two  three
a  1.0  1.0    1.0
b  2.0  2.0    4.0
c  3.0  3.0    9.0
d  NaN  4.0    NaN

In [ ]:
df["flag"] = df["one"] > 2 # boolean column
df

   one  two  three   flag
a  1.0  1.0    1.0  False
b  2.0  2.0    4.0  False
c  3.0  3.0    9.0   True
d  NaN  4.0    NaN  False

In [ ]:
del df["two"] # immediate drop
df

   one  three   flag
a  1.0    1.0  False
b  2.0    4.0  False
c  3.0    9.0   True
d  NaN    NaN  False

In [66]:
three = df.pop("three")
display(three)
type(three)

KeyError: 'three'

In [65]:
df

   one  two   flag
a  1.0  1.0  False
b  2.0  2.0  False
c  3.0  3.0   True
d  NaN  4.0  False

In [68]:
df["foo"] = "bar"

naturally be propagated to fill the column:

In [69]:
df

   one  two   flag  foo
a  1.0  1.0  False  bar
b  2.0  2.0  False  bar
c  3.0  3.0   True  bar
d  NaN  4.0  False  bar

In [70]:
df["one_trunc"] = df["one"][:2]

In [71]:
df

   one  two   flag  foo  one_trunc
a  1.0  1.0  False  bar        1.0
b  2.0  2.0  False  bar        2.0
c  3.0  3.0   True  bar        NaN
d  NaN  4.0  False  bar        NaN

column insert
```python
DataFrame.insert(loc, column, value, allow_duplicates=<no_default>)
```

In [ ]:
del df['bar']
df.insert(1,"bar", df["one"])   # if you want to specify the location of column
df

   one  bar  two   flag  foo  one_trunc
a  1.0  1.0  1.0  False  bar        1.0
b  2.0  2.0  2.0  False  bar        2.0
c  3.0  3.0  3.0   True  bar        NaN
d  NaN  NaN  4.0  False  bar        NaN

In [ ]:
df.insert(-1,"fah",df['one']) # -1 doesn't work

ValueError: unbounded slice

### Indexing / selection

df[col] : returns Series

df.loc[label]  returns Series (select row by label)

df.iloc[loc] returns Series (select row by integer location)

df[5:10] returns empty dataframe

In [94]:
df[['bar','one']]

   bar  one
a  1.0  1.0
b  2.0  2.0
c  3.0  3.0
d  NaN  NaN

In [87]:
df.iloc[0]

one            1.0
bar            1.0
two            1.0
flag         False
foo            bar
one_trunc      1.0
Name: a, dtype: object

In [ ]:
df.loc['a']

NameError: name 'bar' is not defined

In [88]:
df[5:10]

Empty DataFrame
Columns: [one, bar, two, flag, foo, one_trunc]
Index: []