# Merge, join, concatenate and compare

- 모두 고르시오 객관식
- T / F
- output 예상하기
- Series,pandas 비교 | zip,lambda function | broadcasting
- 다음주 10시 시험예정

In [1]:
import pandas as pd

In [2]:
df1 = pd.DataFrame(
    {
        "A": ["A0", "A1", "A2", "A3"],
        "B": ["B0", "B1", "B2", "B3"],
        "C": ["C0", "C1", "C2", "C3"],
        "D": ["D0", "D1", "D2", "D3"],
    },
    index=[0, 1, 2, 3], # [i for i in range(4)]
)


df2 = pd.DataFrame(
    {
        "A": ["A4", "A5", "A6", "A7"],
        "B": ["B4", "B5", "B6", "B7"],
        "C": ["C4", "C5", "C6", "C7"],
        "D": ["D4", "D5", "D6", "D7"],
    },
    index=[4, 5, 6, 7],
)


df3 = pd.DataFrame(
    {
        "A": ["A8", "A9", "A10", "A11"],
        "B": ["B8", "B9", "B10", "B11"],
        "C": ["C8", "C9", "C10", "C11"],
        "D": ["D8", "D9", "D10", "D11"],
    },
    index=[8, 9, 10, 11],
)

In [ ]:
display(df1)
display(df2)
df3

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

    A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

      A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [4]:
frames = [df1, df3, df2] # index sorted by input sequence
result = pd.concat(frames)
result

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7

In [11]:
frames_test = [df3, df1]
result_test = pd.concat(frames_test)
result_test

      A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3

In [ ]:
result_test.reset_index() # generates a column with index values.

   index    A    B    C    D
0      8   A8   B8   C8   D8
1      9   A9   B9   C9   D9
2     10  A10  B10  C10  D10
3     11  A11  B11  C11  D11
4      0   A0   B0   C0   D0
5      1   A1   B1   C1   D1
6      2   A2   B2   C2   D2
7      3   A3   B3   C3   D3

```python
pd.concat(
    objs,
    axis=0,
    join="outer",
    ignore_index=False,
    keys=None,
    levels=None,
    names=None,
    verify_integrity=False,
    copy=True,
)
```

- objs : a sequence or mapping of Series or DataFrame objects. If a dict is passed, the sorted keys will be used as the keys argument, unless it is passed, in which case the values will be selected (see below). Any None objects will be dropped silently unless they are all None in which case a ValueError will be raised.

- axis : {0, 1, …}, default 0. The axis to concatenate along.

- join : {‘inner’, ‘outer’}, default ‘outer’. How to handle indexes on other axis(es). Outer for union and inner for intersection.

- ignore_index : boolean, default False. If True, do not use the index values on the concatenation axis. The resulting axis will be labeled 0, …, n - 1. This is useful if you are concatenating objects where the concatenation axis does not have meaningful indexing information. Note the index values on the other axes are still respected in the join.

- keys : sequence, default None. Construct hierarchical index using the passed keys as the outermost level. If multiple levels passed, should contain tuples.

- levels : list of sequences, default None. Specific levels (unique values) to use for constructing a MultiIndex. Otherwise they will be inferred from the keys.

- names : list, default None. Names for the levels in the resulting hierarchical index.

- verify_integrity : boolean, default False. Check whether the new concatenated axis contains duplicates. This can be very expensive relative to the actual data concatenation.

- copy : boolean, default True. If False, do not copy data unnecessarily.

```python 
ignore_index=True
```

In [13]:
pd.concat(frames_test, ignore_index=True)

     A    B    C    D
0   A8   B8   C8   D8
1   A9   B9   C9   D9
2  A10  B10  C10  D10
3  A11  B11  C11  D11
4   A0   B0   C0   D0
5   A1   B1   C1   D1
6   A2   B2   C2   D2
7   A3   B3   C3   D3

In [14]:
frames

[    A   B   C   D
 0  A0  B0  C0  D0
 1  A1  B1  C1  D1
 2  A2  B2  C2  D2
 3  A3  B3  C3  D3,
       A    B    C    D
 8    A8   B8   C8   D8
 9    A9   B9   C9   D9
 10  A10  B10  C10  D10
 11  A11  B11  C11  D11,
     A   B   C   D
 4  A4  B4  C4  D4
 5  A5  B5  C5  D5
 6  A6  B6  C6  D6
 7  A7  B7  C7  D7]

In [25]:
result = pd.concat(frames, keys=["x", "y", "z"])
result

        A    B    C    D
x 0    A0   B0   C0   D0
  1    A1   B1   C1   D1
  2    A2   B2   C2   D2
  3    A3   B3   C3   D3
y 8    A8   B8   C8   D8
  9    A9   B9   C9   D9
  10  A10  B10  C10  D10
  11  A11  B11  C11  D11
z 4    A4   B4   C4   D4
  5    A5   B5   C5   D5
  6    A6   B6   C6   D6
  7    A7   B7   C7   D7

when you want to use multi-level, you can do so by using the tuples

In [23]:
result = pd.concat(frames, keys=[("x","a"), ("x","b"), ("y","c")])
result

          A    B    C    D
x a 0    A0   B0   C0   D0
    1    A1   B1   C1   D1
    2    A2   B2   C2   D2
    3    A3   B3   C3   D3
  b 8    A8   B8   C8   D8
    9    A9   B9   C9   D9
    10  A10  B10  C10  D10
    11  A11  B11  C11  D11
y c 4    A4   B4   C4   D4
    5    A5   B5   C5   D5
    6    A6   B6   C6   D6
    7    A7   B7   C7   D7

In [31]:
result = pd.concat(frames, keys=["x", "y", "z"])
result

        A    B    C    D
x 0    A0   B0   C0   D0
  1    A1   B1   C1   D1
  2    A2   B2   C2   D2
  3    A3   B3   C3   D3
y 8    A8   B8   C8   D8
  9    A9   B9   C9   D9
  10  A10  B10  C10  D10
  11  A11  B11  C11  D11
z 4    A4   B4   C4   D4
  5    A5   B5   C5   D5
  6    A6   B6   C6   D6
  7    A7   B7   C7   D7

In [32]:
result.loc["y"]

      A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [36]:
result.loc[('x',0):('y',9)]

      A   B   C   D
x 0  A0  B0  C0  D0
  1  A1  B1  C1  D1
  2  A2  B2  C2  D2
  3  A3  B3  C3  D3
y 8  A8  B8  C8  D8
  9  A9  B9  C9  D9

## set logic on the other axes

When gluing together multiple DataFrames, you have a choice of how to handle the other axes (other than the one being concatenated). This can be done in the following two ways:

- Take the union of them all, join='outer'. This is the default option as it results in zero information loss.

- Take the intersection, join='inner'.

In [6]:
df4 = pd.DataFrame(
    {
        "B": ["B2", "B3", "B6", "B7"],
        "D": ["D2", "D3", "D6", "D7"],
        "F": ["F2", "F3", "F6", "F7"],
    },
    index=[2, 3, 6, 7],
)
display(df1)
df4

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

    B   D   F
2  B2  D2  F2
3  B3  D3  F3
6  B6  D6  F6
7  B7  D7  F7

In [38]:
result = pd.concat([df1, df4], axis=1)
result

     A    B    C    D    B    D    F
0   A0   B0   C0   D0  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN
2   A2   B2   C2   D2   B2   D2   F2
3   A3   B3   C3   D3   B3   D3   F3
6  NaN  NaN  NaN  NaN   B6   D6   F6
7  NaN  NaN  NaN  NaN   B7   D7   F7

In [41]:
result = pd.concat([df1, df4], axis=1, join="inner")
result

    A   B   C   D   B   D   F
2  A2  B2  C2  D2  B2  D2  F2
3  A3  B3  C3  D3  B3  D3  F3

when you want to reuse the exact index from the original DataFrame:

In [42]:
result = pd.concat([df1, df4], axis=1).reindex(df1.index)
result

    A   B   C   D    B    D    F
0  A0  B0  C0  D0  NaN  NaN  NaN
1  A1  B1  C1  D1  NaN  NaN  NaN
2  A2  B2  C2  D2   B2   D2   F2
3  A3  B3  C3  D3   B3   D3   F3

## Ignoring indexes on the concatenation axis

For DataFrame objects which don’t have a meaningful index, you may wish to append them and ignore the fact that they may have overlapping indexes. To do this, use the ignore_index argument:

In [11]:
df1

    A   B   C   D
a  A0  B0  C0  D0
b  A1  B1  C1  D1
c  A2  B2  C2  D2
d  A3  B3  C3  D3

In [10]:
df1.index = list('abcd')

In [ ]:
result = pd.concat([df1, df4], sort=False)
result

     A   B    C   D    F
a   A0  B0   C0  D0  NaN
b   A1  B1   C1  D1  NaN
c   A2  B2   C2  D2  NaN
d   A3  B3   C3  D3  NaN
2  NaN  B2  NaN  D2   F2
3  NaN  B3  NaN  D3   F3
6  NaN  B6  NaN  D6   F6
7  NaN  B7  NaN  D7   F7

## Concatenating with mixed ndims

In [44]:
s1 = pd.Series(["X0", "X1", "X2", "X3"], name="X")
s1

0    X0
1    X1
2    X2
3    X3
Name: X, dtype: object

In [45]:
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [46]:
result = pd.concat([df1, s1], axis=1)
result

    A   B   C   D   X
0  A0  B0  C0  D0  X0
1  A1  B1  C1  D1  X1
2  A2  B2  C2  D2  X2
3  A3  B3  C3  D3  X3

Passing  ```python (ignore_index=True)``` will drop all name references. (몰라도 되는 기술)

In [47]:
result = pd.concat([df1, s1], axis=1, ignore_index=True)
result

    0   1   2   3   4
0  A0  B0  C0  D0  X0
1  A1  B1  C1  D1  X1
2  A2  B2  C2  D2  X2
3  A3  B3  C3  D3  X3

## More concatenating with group keys

A fairly common use of the keys argument is to override the column names when creating a new DataFrame based on existing Series. Notice how the default behaviour consists on letting the resulting DataFrame inherit the parent Series’ name, when these existed.

In [14]:
s3 = pd.Series([0, 1, 2, 3], name="foo")

s4 = pd.Series([0, 1, 2, 3])

s5 = pd.Series([0, 1, 4, 5])

pd.concat([s3, s4, s5], axis=1)

   foo  0  1
0    0  0  0
1    1  1  1
2    2  2  4
3    3  3  5

In [29]:
pd.concat([s3, s4, s5], axis=1, keys=["red", "blue", "yellow"])

   red  blue  yellow
0    0     0       0
1    1     1       1
2    2     2       4
3    3     3       5

In [50]:
result = pd.concat(frames, keys=["x", "y", "z"])
result

        A    B    C    D
x 0    A0   B0   C0   D0
  1    A1   B1   C1   D1
  2    A2   B2   C2   D2
  3    A3   B3   C3   D3
y 8    A8   B8   C8   D8
  9    A9   B9   C9   D9
  10  A10  B10  C10  D10
  11  A11  B11  C11  D11
z 4    A4   B4   C4   D4
  5    A5   B5   C5   D5
  6    A6   B6   C6   D6
  7    A7   B7   C7   D7

In [52]:
pieces = {'x':s3,'y':s4,'z':s5}
pd.concat(pieces,axis=1)

   x  y  z
0  0  0  0
1  1  1  1
2  2  2  4
3  3  3  5

In [51]:
pieces = {"x": df1, "y": df2, "z": df3}
result = pd.concat(pieces)
result

        A    B    C    D
x 0    A0   B0   C0   D0
  1    A1   B1   C1   D1
  2    A2   B2   C2   D2
  3    A3   B3   C3   D3
y 4    A4   B4   C4   D4
  5    A5   B5   C5   D5
  6    A6   B6   C6   D6
  7    A7   B7   C7   D7
z 8    A8   B8   C8   D8
  9    A9   B9   C9   D9
  10  A10  B10  C10  D10
  11  A11  B11  C11  D11

In [57]:
result = pd.concat(pieces, keys=["z", "y"])
result

z  0    0
   1    1
   2    4
   3    5
y  0    0
   1    1
   2    2
   3    3
dtype: int64

## Appending rows to a DataFrame

If you have a series that you want to append as a single row to a DataFrame, **you can convert the row into a DataFrame and use concat**

In [31]:
s2 = pd.Series(["X0", "X1", "X2", "X3"], index=["A", "B", "C", "D"])
s2

A    X0
B    X1
C    X2
D    X3
dtype: object

In [35]:
result = pd.concat([df1, s2.T.to_frame()], ignore_index=True)
result

     A    B    C    D    0
0   A0   B0   C0   D0  NaN
1   A1   B1   C1   D1  NaN
2   A2   B2   C2   D2  NaN
3   A3   B3   C3   D3  NaN
4  NaN  NaN  NaN  NaN   X0
5  NaN  NaN  NaN  NaN   X1
6  NaN  NaN  NaN  NaN   X2
7  NaN  NaN  NaN  NaN   X3

In [33]:
result = pd.concat([df1, s2.to_frame().T], ignore_index=True)
result

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  X0  X1  X2  X3

In [34]:
result = pd.concat([df1, s2.to_frame().T])
result

    A   B   C   D
a  A0  B0  C0  D0
b  A1  B1  C1  D1
c  A2  B2  C2  D2
d  A3  B3  C3  D3
0  X0  X1  X2  X3